// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { GetVenueData, GetVenueResponse, GetTimelineData, GetTimelineResponse, GetDemoTickData, GetDemoTickResponse, GetDemoTickError, DemoResetData, DemoResetResponse, ModelStatusData, ModelStatusResponse, AnalyzeData, AnalyzeResponse, AnalyzeError, HealthData, HealthResponse2 } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Venue
 */
export const getVenue = <ThrowOnError extends boolean = false>(options?: Options<GetVenueData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetVenueResponse, unknown, ThrowOnError>({
        url: '/api/venue',
        ...options
    });
};

/**
 * Get Timeline
 */
export const getTimeline = <ThrowOnError extends boolean = false>(options?: Options<GetTimelineData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTimelineResponse, unknown, ThrowOnError>({
        url: '/api/demo/timeline',
        ...options
    });
};

/**
 * Get Demo Tick
 */
export const getDemoTick = <ThrowOnError extends boolean = false>(options?: Options<GetDemoTickData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDemoTickResponse, GetDemoTickError, ThrowOnError>({
        url: '/api/demo/tick',
        ...options
    });
};

/**
 * Demo Reset
 */
export const demoReset = <ThrowOnError extends boolean = false>(options?: Options<DemoResetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DemoResetResponse, unknown, ThrowOnError>({
        url: '/api/demo/reset',
        ...options
    });
};

/**
 * Model Status
 */
export const modelStatus = <ThrowOnError extends boolean = false>(options?: Options<ModelStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ModelStatusResponse, unknown, ThrowOnError>({
        url: '/api/model/status',
        ...options
    });
};

/**
 * Analyze
 */
export const analyze = <ThrowOnError extends boolean = false>(options: Options<AnalyzeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AnalyzeResponse, AnalyzeError, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/analyze',
        ...options,
        headers: {
            'Content-Type': null,
            ...options?.headers
        }
    });
};

/**
 * Health
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthResponse2, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};