// This file is auto-generated by @hey-api/openapi-ts

export type BodyOpsAnalyze = {
    file: Blob | File;
    phase?: string | null;
    reset?: boolean;
};

export type DemoTimeline = {
    duration_sec: number;
    frames: Array<TimelineFrame>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthResponse = {
    status: string;
};

export type ModelMeta = {
    source: string;
    model_repo: string;
    global_count: number;
    ready: boolean;
    error?: string | null;
};

export type ModelStatus = {
    ready: boolean;
    device: string;
    repo: string;
    dataset: string;
    error?: string | null;
};

export type OkResponse = {
    ok: boolean;
};

export type RouteSuggestion = {
    from: string;
    to: string;
    avoid_zones?: Array<string> | null;
    path: Array<string>;
    path_labels: Array<string>;
    message: string;
};

export type Snapshot = {
    venue_id: string;
    venue_name: string;
    t?: number | null;
    phase?: string | null;
    note?: string | null;
    zones: Array<ZoneSnapshot>;
    bottlenecks: Array<string>;
    routes: Array<RouteSuggestion>;
    suggestion: string;
    model: ModelMeta;
    history: {
        [key: string]: Array<number>;
    };
};

export type TimelineFrame = {
    t: number;
    phase: string;
    note: string;
    densities: {
        [key: string]: number;
    };
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type Venue = {
    id: string;
    name: string;
    width: number;
    height: number;
    zones: Array<VenueZone>;
    graph: VenueGraph;
};

export type VenueGraph = {
    nodes: Array<string>;
    edges: Array<{
        [key: string]: unknown;
    }>;
};

export type VenueZone = {
    id: string;
    label: string;
    type: string;
    capacity: number;
    polygon: Array<Array<number>>;
    centroid: Array<number>;
};

export type ZoneSnapshot = {
    id: string;
    label: string;
    type: string;
    capacity: number;
    count_est: number;
    density: number;
    risk: 'low' | 'medium' | 'high' | 'critical';
    centroid: Array<number>;
    polygon: Array<Array<number>>;
    trend?: string | null;
};

export type GetVenueData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/venue';
};

export type GetVenueResponses = {
    /**
     * Successful Response
     */
    200: Venue;
};

export type GetVenueResponse = GetVenueResponses[keyof GetVenueResponses];

export type GetTimelineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/timeline';
};

export type GetTimelineResponses = {
    /**
     * Successful Response
     */
    200: DemoTimeline;
};

export type GetTimelineResponse = GetTimelineResponses[keyof GetTimelineResponses];

export type GetDemoTickData = {
    body?: never;
    path?: never;
    query?: {
        t?: number;
    };
    url: '/api/demo/tick';
};

export type GetDemoTickErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDemoTickError = GetDemoTickErrors[keyof GetDemoTickErrors];

export type GetDemoTickResponses = {
    /**
     * Successful Response
     */
    200: Snapshot;
};

export type GetDemoTickResponse = GetDemoTickResponses[keyof GetDemoTickResponses];

export type DemoResetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/demo/reset';
};

export type DemoResetResponses = {
    /**
     * Successful Response
     */
    200: OkResponse;
};

export type DemoResetResponse = DemoResetResponses[keyof DemoResetResponses];

export type ModelStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/model/status';
};

export type ModelStatusResponses = {
    /**
     * Successful Response
     */
    200: ModelStatus;
};

export type ModelStatusResponse = ModelStatusResponses[keyof ModelStatusResponses];

export type AnalyzeData = {
    body: BodyOpsAnalyze;
    path?: never;
    query?: never;
    url: '/api/analyze';
};

export type AnalyzeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalyzeError = AnalyzeErrors[keyof AnalyzeErrors];

export type AnalyzeResponses = {
    /**
     * Successful Response
     */
    200: Snapshot;
};

export type AnalyzeResponse = AnalyzeResponses[keyof AnalyzeResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};